[build]
  command = "cd server && npm install && cd ../client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 #

[[redirects]]
  from = "/(img/*|favicon.ico|manifest.json|logo*.png|logo*.jpg|logo*.svg)" # Додайте інші типи/шляхи, якщо потрібно
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200